services:
  tickle-fe:
    container_name: tickle-fe
    build:
      context: ./view/fe/tickle
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_AUTH_API_URL: ${NEXT_PUBLIC_AUTH_API_URL}
        NEXT_PUBLIC_AI_PUBLIC_API_URL: ${NEXT_PUBLIC_AI_PUBLIC_API_URL}
        NEXT_PUBLIC_API_MOCKING: ${NEXT_PUBLIC_API_MOCKING}
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./view/fe/tickle/.env
    environment:
      - NODE_ENV=production
      - PORT=3000