import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MSWProvider } from "@/src/shared/providers/MSWProvider";
import { QueryProvider } from "@/src/shared/providers/QueryProvider";
import { AuthProvider } from "@/src/shared/providers/AuthProvider";
import { ToastProvider } from "@/src/shared/providers/ToastProvider";
import { BotDetector } from "@/src/shared/components/BotDetector";
import { TRIAL_CONFIG } from "../../trialConfig";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tickle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MSWProvider>
          <QueryProvider>
            <AuthProvider>
              <ToastProvider>
                {TRIAL_CONFIG.ENABLE_BOT_DETECTOR ? (
                  <BotDetector>{children}</BotDetector>
                ) : (
                  children
                )}
              </ToastProvider>
            </AuthProvider>
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
