FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --no-frozen-lockfile --shamefully-hoist

COPY . .

EXPOSE 3000

CMD ["pnpm", "start"]
