# infra/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'server1-be'
    static_configs:
      - targets: ['172.31.63.75:9090']
  - job_name: 'server2-kafka'
    static_configs:
      - targets: ['172.31.52.183:9090']
  - job_name: 'server4-auth'
    static_configs:
      - targets: ['172.31.57.10:9090']