# infra/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'server1-node'
    static_configs:
      - targets: ['172.31.63.75:9100']
        labels:
          server: 'server1-BE'

  - job_name: 'server2-node'
    static_configs:
      - targets: ['172.31.52.183:9100']
        labels:
          server: 'server2-Kafka'

  - job_name: 'server3-node'
    static_configs:
      - targets: ['172.31.57.10:9100']
        labels:
          server: 'server3-Monitoring'

  - job_name: 'server4-node'
    static_configs:
      - targets: ['172.31.62.10:9100']
        labels:
          server: 'server4-Auth'

  - job_name: 'server5-node'
    static_configs:
      - targets: ['172.31.56.122:9100']
        labels:
          server: 'server5-Jenkins'

  # ── Spring Boot 애플리케이션 메트릭 ──
  - job_name: 'server1-be'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.31.63.75:8080']
        labels:
          server: 'server1-BE'

  - job_name: 'server4-auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.31.62.10:8080']
        labels:
          server: 'server4-Auth'