# infra/redis/sentinel-server3.conf
port 26379
sentinel announce-ip 172.31.57.10
sentinel announce-port 26379
sentinel monitor mymaster 172.31.63.75 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 60000
sentinel parallel-syncs mymaster 1